defmodule TechtreeWeb.Endpoint do
  @moduledoc """
  Everything a request passes through before the routing table sees it.

  This application publishes, and accepts two documents at exactly one address —
  a finished run and a signed withdrawal of one — and the pipeline is built so
  that this stays true by construction rather than by nobody having added a
  route yet. There is no multipart parser,
  so a body of files is never read, never spooled to disk, and never held in
  memory on its way to a refusal. There is no method override, so a hidden
  parameter cannot turn a request into a verb the routing table does not
  answer. And a static file is served with the same refusals a page is, because
  a file opened directly in a browser is a document like any other.

  The parser reads at most the publication cap from any address, so a body
  larger than the one document this site accepts is stopped before it is
  decoded, wherever it was sent. The one address that does take a body is also
  guarded before the parser: `TechtreeWeb.PublicationRate` refuses a caller who
  is over the limit before their body is read, and `TechtreeWeb.PublicationBody`
  keeps the exact bytes for the checks made against a digest of them.
  """

  use Phoenix.Endpoint, otp_app: :techtree

  import Phoenix.Controller, only: [put_secure_browser_headers: 2]

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_techtree_key",
    signing_salt: "ESr0k/Zc",
    same_site: "Lax"
  ]

  # A stylesheet, an icon, or an image may be navigated to directly, and then
  # the browser is reading it as a document. These say what a document from
  # this host may do, which is nothing.
  @static_headers %{
    "content-security-policy" => "default-src 'none'; frame-ancestors 'none'",
    "x-content-type-options" => "nosniff",
    "x-frame-options" => "DENY",
    "referrer-policy" => "no-referrer"
  }

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  plug TechtreeWeb.Plugs.CanonicalHost
  plug TechtreeWeb.SourceRevision

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # `only` names the published files; `only_matching` also lets their
  # digested variants through — `phx.digest` renames a file to
  # `name-<hash>.ext` and `~p` emits that name, which `only` alone refuses.
  plug Plug.Static,
    at: "/",
    from: :techtree,
    gzip: not code_reloading?,
    only: TechtreeWeb.static_paths(),
    only_matching: ~w(favicon apple-touch-icon robots),
    raise_on_missing_only: code_reloading?,
    headers: @static_headers

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :techtree
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Before the parser, so a caller over the publication limit costs no read.
  plug TechtreeWeb.PublicationRate

  # Every page, and every Markdown or refusal the next plug answers before the
  # router, carries these. Browser agents may use the tools every page
  # registers, from this site only. API responses replace them with their own.
  plug :secure_browser_headers

  # Before the parser, so a body it refuses on an `/api` path is answered
  # in JSON (`TechtreeWeb.Plugs.Parsers`).
  plug RegentAgentAccess.Plug,
    documents: &TechtreeWeb.PublicDocuments.document/1,
    guide: "/llms.txt"

  # One route reads a request body, and nothing here needs to accept a file. A
  # body in a content type this does not parse is passed along untouched and
  # meets the same refusal it would have met anyway. No address accepts more
  # than the publication cap (`Techtree.Network.maximum_body_bytes/0`).
  plug TechtreeWeb.Plugs.Parsers,
    parsers: [:urlencoded, :json],
    pass: ["*/*"],
    length: Application.compile_env!(:techtree, [Techtree.Network, :maximum_body_bytes]),
    body_reader: {TechtreeWeb.PublicationBody, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.Head
  plug Plug.Session, @session_options

  plug TechtreeWeb.MethodSurface
  plug TechtreeWeb.Router

  defp secure_browser_headers(conn, _opts) do
    put_secure_browser_headers(conn, %{
      "content-security-policy" => TechtreeWeb.ContentSecurityPolicy.reading(),
      "referrer-policy" => "no-referrer",
      "permissions-policy" => "tools=(self)"
    })
  end
end
