defmodule Techtree.Repo.Migrations.AddSafetyRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:safety_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :test_slug, :text, null: false
      add :test_version, :bigint, null: false
      add :monitor_a, :text, null: false
      add :monitor_b, :text, null: false
      add :model, :text, null: false
      add :case_count, :bigint, null: false
      add :status, :text, null: false, default: "running"
      add :verdicts, {:array, :map}, null: false, default: []
      add :failure, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :finished_at, :utc_datetime_usec
    end
  end

  def down do
    drop table(:safety_runs)
  end
end
