defmodule Techtree.Repo.Migrations.TechtreeUnifiedAccess do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:network_publication_events) do
      add :beneficiary_privy_user_id, :text
      add :acting_agent_wallet, :text
      add :pairing_id, :uuid
    end
  end

  def down do
    alter table(:network_publication_events) do
      remove :pairing_id
      remove :acting_agent_wallet
      remove :beneficiary_privy_user_id
    end
  end
end
