defmodule Techtree.Repo.Migrations.StorePublicationAssessments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:network_publication_entries) do
      add :assessment, :map
      modify :skill_digest, :text, null: false
    end
  end

  def down do
    alter table(:network_publication_entries) do
      modify :skill_digest, :text, null: true
      remove :assessment
    end
  end
end
