defmodule Techtree.Repo.Migrations.StoreWithdrawalReceipts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:network_publication_entries) do
      add :withdrawal_receipt_bytes, :binary
      add :withdrawal_receipt_digest, :text
      add :withdrawal_network_key_id, :text
    end

    create constraint(:network_publication_entries, :withdrawn_with_receipt,
             check: """
               withdrawn_at IS NULL OR (withdrawal_receipt_bytes IS NOT NULL AND withdrawal_receipt_digest IS NOT NULL AND withdrawal_network_key_id IS NOT NULL)
             """
           )

    create unique_index(:network_publication_events, [:publication_entry_id, :kind],
             name: "network_publication_events_one_event_of_each_kind_index"
           )
  end

  def down do
    drop_if_exists unique_index(:network_publication_events, [:publication_entry_id, :kind],
                     name: "network_publication_events_one_event_of_each_kind_index"
                   )

    drop_if_exists constraint(:network_publication_entries, :withdrawn_with_receipt)

    alter table(:network_publication_entries) do
      remove :withdrawal_network_key_id
      remove :withdrawal_receipt_digest
      remove :withdrawal_receipt_bytes
    end
  end
end
