"""Techtree protocol models. Spec section 11.1.

This package exports only stable model classes. It never imports services, CLI
code, resources, or settings, and no model file reaches back into
:mod:`techtree.canonical` — models describe documents, they do not hash them.

Exports are grouped the way the protocol is layered:

Campaign and public wrapper
    The scientific contract and the public invitation that wraps it.

Execution artifacts
    Everything one run produces, all of it anchored to a Campaign digest.

Taskset validation
    The lock, the deterministic receipt, and the local execution record.

The v0.2 evidence contract
    The orthogonal evidence facets a proof carries, and the estimate and
    approval that authorize the spend a run makes.

Catalog, CLI, and local state
    What the packaged catalog ships and what the CLI hands back.
"""

from __future__ import annotations

from techtree.models.approval import (
    ApprovalMethod,
    ArmCeilings,
    CeilingScope,
    ExecutionApproval,
    MonetaryAmount,
    RemoteExecutionEstimate,
)
from techtree.models.base import (
    ArtifactRef,
    Digest,
    JsonScalar,
    JsonValue,
    NonEmptyString,
    ObjectEnvelope,
    ProtocolModel,
    PublicKeyRef,
    SignatureEnvelope,
    StateModel,
    UtcDateTime,
)

# --- Campaign and public wrapper -------------------------------------------
from techtree.models.campaign import (
    AgentSpec,
    AgentSpecV2,
    BudgetSpec,
    CampaignContext,
    CampaignMetadata,
    CampaignSpec,
    CampaignSpecV2,
    CampaignTaskset,
    EnvironmentSpec,
    EvidenceRequirements,
    EvidenceRequirementsV2,
    ExecutionSpec,
    HarnessSpec,
    HarnessSpecV2,
    ModelSpec,
    MutationContract,
    PackageRef,
    ProgramRef,
    PublicContext,
    RuntimeSpec,
    SamplingSpec,
    ScoringSpec,
    TaskMembershipCommitment,
    TaskSelection,
    TasksetRef,
)
from techtree.models.catalog import (
    CatalogClimbEntry,
    CatalogIndex,
    CatalogObjectLocation,
    ClimbSummary,
    CompatibilityIssue,
    CompatibilityResult,
    DataPolicySummary,
    EngineCompatibilityStatus,
)

# --- Catalog, CLI, and local state -----------------------------------------
from techtree.models.cli import (
    CheckStatus,
    CliEnvelope,
    CliError,
    CliMessage,
    DoctorCheck,
    MessageLevel,
    NextAction,
)
from techtree.models.climb import (
    CandidateConstraints,
    CandidatePolicy,
    ClimbManifest,
    ClimbMetadata,
    LeaderboardPolicy,
    PublicationPolicy,
    ResolvedClimb,
    check_climb_policy_consistency,
)
from techtree.models.compatibility import (
    CompatibilityVerdict,
    ConfigurationComparison,
    ConfigurationCompatibilityPolicy,
    JsonPointer,
)
from techtree.models.data_policy import (
    CandidateSkillPolicy,
    DataOwner,
    DataPolicy,
    DerivedArtifactPolicy,
    RawEpisodePolicy,
    RevocationPolicy,
)
from techtree.models.engine import (
    EngineDescriptor,
    EngineInstallation,
    EnginePackage,
    EngineStatus,
    HostPlatform,
    normalize_host_platform,
)

# --- Execution artifacts ---------------------------------------------------
from techtree.models.episode_receipt import (
    EpisodeReceipt,
    EvidenceStatus,
    NamedTraceReceipt,
    ScoreStatus,
    SubjectRuntimeReceipt,
)
from techtree.models.evaluation_backend import (
    AttestationKind,
    EvaluationBackendKind,
    EvaluationBackendSpec,
)

# --- The v0.2 evidence contract --------------------------------------------
from techtree.models.evidence import (
    ArtifactIntegrity,
    ArtifactIntegrityStatus,
    ComparisonValidity,
    ComparisonValidityStatus,
    EvidenceArtifactRef,
    EvidenceFacets,
    ExecutionLocation,
    ExecutionLocationKind,
    ExecutionObservation,
    ModelIdentity,
    ModelPinStrength,
    ParticipantAttestation,
    ParticipantAttestationStatus,
    ProviderAttestation,
    ProviderAttestationStatus,
    ProviderRecord,
    ProviderRecordStatus,
    ProviderVerificationClaim,
    ReproductionKind,
    ReproductionRef,
    TraceCoverage,
    TraceCoverageKind,
    independent_reproductions,
    is_independent_reproduction,
    may_headline_uplift,
    provider_verification_claim,
)
from techtree.models.execution_plan import (
    EvaluationEngineRef,
    EvidenceBackendSpec,
    ExecutionBackendKind,
    ExecutionBackendSpec,
    ExecutionProvider,
    ResolvedExecutionPlan,
    SubjectBackendKind,
    SubjectBackendSpec,
)
from techtree.models.experiment import (
    ExperimentConfiguration,
    ExperimentManifest,
    ExperimentVariant,
    JsonDifference,
    ManifestComparison,
)
from techtree.models.run import (
    PolicyAcknowledgement,
    RunEvent,
    RunPhase,
    RunProgress,
    RunRequest,
    RunState,
    RunStatus,
)
from techtree.models.skill import (
    PolicyAcceptanceRequirement,
    SkillArtifact,
    SkillFile,
    SubmissionDraft,
)
from techtree.models.uplift_report import (
    ComparisonStatus,
    ExecutionStatus,
    PrimaryUpliftResult,
    PublicationStatus,
    TaskDelta,
    UpliftDecision,
    UpliftReport,
    UpliftStatuses,
)

# --- Taskset validation ----------------------------------------------------
from techtree.models.validation import (
    TasksetLock,
    TasksetValidationReceipt,
    UpstreamValidationSummary,
    ValidationCheck,
    ValidationEvidence,
    ValidationEvidenceSummary,
    ValidationEvidenceTask,
    ValidationExecutionRecord,
    ValidationMethod,
    ValidationTaskOutcome,
    validation_display_id,
)

__all__ = [
    "AgentSpec",
    "AgentSpecV2",
    "ApprovalMethod",
    "ArmCeilings",
    "ArtifactIntegrity",
    "ArtifactIntegrityStatus",
    "ArtifactRef",
    "AttestationKind",
    "BudgetSpec",
    "CampaignContext",
    "CampaignMetadata",
    "CampaignSpec",
    "CampaignSpecV2",
    "CampaignTaskset",
    "CandidateConstraints",
    "CandidatePolicy",
    "CandidateSkillPolicy",
    "CatalogClimbEntry",
    "CatalogIndex",
    "CatalogObjectLocation",
    "CeilingScope",
    "CheckStatus",
    "CliEnvelope",
    "CliError",
    "CliMessage",
    "ClimbManifest",
    "ClimbMetadata",
    "ClimbSummary",
    "ComparisonStatus",
    "ComparisonValidity",
    "ComparisonValidityStatus",
    "CompatibilityIssue",
    "CompatibilityResult",
    "CompatibilityVerdict",
    "ConfigurationComparison",
    "ConfigurationCompatibilityPolicy",
    "DataOwner",
    "DataPolicy",
    "DataPolicySummary",
    "DerivedArtifactPolicy",
    "Digest",
    "DoctorCheck",
    "EngineCompatibilityStatus",
    "EngineDescriptor",
    "EngineInstallation",
    "EnginePackage",
    "EngineStatus",
    "EnvironmentSpec",
    "EpisodeReceipt",
    "EvaluationBackendKind",
    "EvaluationBackendSpec",
    "EvaluationEngineRef",
    "EvidenceArtifactRef",
    "EvidenceBackendSpec",
    "EvidenceFacets",
    "EvidenceRequirements",
    "EvidenceRequirementsV2",
    "EvidenceStatus",
    "ExecutionApproval",
    "ExecutionBackendKind",
    "ExecutionBackendSpec",
    "ExecutionLocation",
    "ExecutionLocationKind",
    "ExecutionObservation",
    "ExecutionProvider",
    "ExecutionSpec",
    "ExecutionStatus",
    "ExperimentConfiguration",
    "ExperimentManifest",
    "ExperimentVariant",
    "HarnessSpec",
    "HarnessSpecV2",
    "HostPlatform",
    "JsonDifference",
    "JsonPointer",
    "JsonScalar",
    "JsonValue",
    "LeaderboardPolicy",
    "ManifestComparison",
    "MessageLevel",
    "ModelIdentity",
    "ModelPinStrength",
    "ModelSpec",
    "MonetaryAmount",
    "MutationContract",
    "NamedTraceReceipt",
    "NextAction",
    "NonEmptyString",
    "ObjectEnvelope",
    "PackageRef",
    "ParticipantAttestation",
    "ParticipantAttestationStatus",
    "PolicyAcceptanceRequirement",
    "PolicyAcknowledgement",
    "PrimaryUpliftResult",
    "ProgramRef",
    "ProtocolModel",
    "ProviderAttestation",
    "ProviderAttestationStatus",
    "ProviderRecord",
    "ProviderRecordStatus",
    "ProviderVerificationClaim",
    "PublicContext",
    "PublicKeyRef",
    "PublicationPolicy",
    "PublicationStatus",
    "RawEpisodePolicy",
    "RemoteExecutionEstimate",
    "ReproductionKind",
    "ReproductionRef",
    "ResolvedClimb",
    "ResolvedExecutionPlan",
    "RevocationPolicy",
    "RunEvent",
    "RunPhase",
    "RunProgress",
    "RunRequest",
    "RunState",
    "RunStatus",
    "RuntimeSpec",
    "SamplingSpec",
    "ScoreStatus",
    "ScoringSpec",
    "SignatureEnvelope",
    "SkillArtifact",
    "SkillFile",
    "StateModel",
    "SubjectBackendKind",
    "SubjectBackendSpec",
    "SubjectRuntimeReceipt",
    "SubmissionDraft",
    "TaskDelta",
    "TaskMembershipCommitment",
    "TaskSelection",
    "TasksetLock",
    "TasksetRef",
    "TasksetValidationReceipt",
    "TraceCoverage",
    "TraceCoverageKind",
    "UpliftDecision",
    "UpliftReport",
    "UpliftStatuses",
    "UpstreamValidationSummary",
    "UtcDateTime",
    "ValidationCheck",
    "ValidationEvidence",
    "ValidationEvidenceSummary",
    "ValidationEvidenceTask",
    "ValidationExecutionRecord",
    "ValidationMethod",
    "ValidationTaskOutcome",
    "check_climb_policy_consistency",
    "independent_reproductions",
    "is_independent_reproduction",
    "may_headline_uplift",
    "normalize_host_platform",
    "provider_verification_claim",
    "validation_display_id",
]
